version: '3'
services:
    redis:
        image: "redis:latest"
        container_name: "redis"
        ports:
            - "6379:6379"
        dns:
            - 8.8.8.8
            - 8.8.8.4
        volumes:
            - ./redis-manager-school:/var/lib/redis
        networks:
            - redis-network
    app:
        build: .
        command: go run main.go
        networks:
            - redis-network
        depends_on:
            - redis
        volumes:
            - .:/app
        working_dir: /app
networks:
    redis-network:
        driver: bridge